// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpR4P95ehxX3iN0IwLjVM8KFWP6JCN33Q',
    appId: '1:760131924547:web:9e93ae9834f848699fdaf6',
    messagingSenderId: '760131924547',
    projectId: 'teamfinder-e7048',
    authDomain: 'teamfinder-e7048.firebaseapp.com',
    storageBucket: 'teamfinder-e7048.appspot.com',
    measurementId: 'G-Q0LNWXCFB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNCb5boGaOGAi0EmhMcRGiQK-0JBJNA4',
    appId: '1:760131924547:android:00d43ba950a4cc499fdaf6',
    messagingSenderId: '760131924547',
    projectId: 'teamfinder-e7048',
    storageBucket: 'teamfinder-e7048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFp6LX1nT66m606yYMLWkSoyqO5yPbxo',
    appId: '1:760131924547:ios:d036ba756470e0be9fdaf6',
    messagingSenderId: '760131924547',
    projectId: 'teamfinder-e7048',
    storageBucket: 'teamfinder-e7048.appspot.com',
    androidClientId: '760131924547-55kmb1eh6cq318o8k3tg3shmssfh79kb.apps.googleusercontent.com',
    iosClientId: '760131924547-lbun8c7ktspmgkqe2bgj7vtqmpju5vfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamfinderMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoFp6LX1nT66m606yYMLWkSoyqO5yPbxo',
    appId: '1:760131924547:ios:d4fbb3454acad3c79fdaf6',
    messagingSenderId: '760131924547',
    projectId: 'teamfinder-e7048',
    storageBucket: 'teamfinder-e7048.appspot.com',
    androidClientId: '760131924547-55kmb1eh6cq318o8k3tg3shmssfh79kb.apps.googleusercontent.com',
    iosClientId: '760131924547-mgab04bvvvvtltfi1jondttcthvv8eb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamfinderMobile.RunnerTests',
  );
}
